// src/services/metadata.js
// NFT Metadata Generator Service - Creates ERC-721 compatible JSON metadata

const fs = require('fs').promises;
const path = require('path');
const supabase = require('../config/supabase');

/**
 * Generate ERC-721 compatible metadata for a single NFT
 * @param {Object} params - Metadata parameters
 * @param {string} params.projectId - UUID of the project
 * @param {number} params.tokenId - Token ID (1, 2, 3, ...)
 * @param {string} params.name - NFT name (e.g., "Project Name #1")
 * @param {string} params.description - NFT description
 * @param {string} params.imageUrl - URL or placeholder for the image
 * @param {Array} params.attributes - Array of {trait_type, value} objects
 * @returns {Object} ERC-721 metadata object
 */
function generateMetadata({ projectId, tokenId, name, description, imageUrl, attributes }) {
  return {
    name: name || `NFT #${tokenId}`,
    description: description || 'Generated by CRO212HUB NFT Generator',
    image: imageUrl || `ipfs://PLACEHOLDER/${tokenId}.png`,
    attributes: attributes || [],
    // Additional metadata fields (optional but common)
    token_id: tokenId,
    external_url: `https://cro212hub.com/nft/${projectId}/${tokenId}`,
    background_color: null
  };
}

/**
 * Save metadata to JSON file
 * @param {string} projectId - UUID of the project
 * @param {number} tokenId - Token ID
 * @param {Object} metadata - Metadata object to save
 * @returns {Promise<string>} Path to the saved file
 */
async function saveMetadataFile(projectId, tokenId, metadata) {
  const metadataDir = path.join(process.cwd(), 'output', projectId, 'metadata');
  const metadataPath = path.join(metadataDir, `${tokenId}.json`);

  // Ensure directory exists
  await fs.mkdir(metadataDir, { recursive: true });

  // Write metadata as formatted JSON
  await fs.writeFile(metadataPath, JSON.stringify(metadata, null, 2), 'utf8');

  return `output/${projectId}/metadata/${tokenId}.json`;
}

/**
 * Save metadata to Supabase database
 * @param {string} projectId - UUID of the project
 * @param {number} tokenId - Token ID
 * @param {string} imagePath - Path to the generated image
 * @param {string} metadataPath - Path to the metadata JSON file
 * @param {Array} attributes - Token attributes
 * @returns {Promise<Object>} Inserted database record
 */
async function saveMetadataToDatabase(projectId, tokenId, imagePath, metadataPath, attributes) {
  const { data, error } = await supabase
    .from('cro_212hub_generated_tokens')
    .insert({
      project_id: projectId,
      token_id: tokenId,
      image_path: imagePath,
      metadata_path: metadataPath,
      attributes: attributes
    })
    .select()
    .single();

  if (error) {
    // If it's a duplicate, update instead
    if (error.code === '23505') {
      const { data: updated, error: updateError } = await supabase
        .from('cro_212hub_generated_tokens')
        .update({
          image_path: imagePath,
          metadata_path: metadataPath,
          attributes: attributes
        })
        .eq('project_id', projectId)
        .eq('token_id', tokenId)
        .select()
        .single();

      if (updateError) {
        throw new Error(`Failed to update metadata in database: ${updateError.message}`);
      }

      return updated;
    }

    throw new Error(`Failed to save metadata to database: ${error.message}`);
  }

  return data;
}

/**
 * Generate and save complete metadata for a single NFT
 * @param {Object} params - Parameters for metadata generation
 * @returns {Promise<Object>} Complete metadata with file paths
 */
async function generateAndSaveMetadata(params) {
  const {
    projectId,
    projectName,
    tokenId,
    imagePath,
    attributes,
    description,
    baseUri = null
  } = params;

  // Construct image URL
  let imageUrl;
  if (baseUri) {
    // Use provided base URI
    // Ensure base URI ends with / for proper concatenation
    const normalizedBaseUri = baseUri.endsWith('/') ? baseUri : `${baseUri}/`;
    imageUrl = `${normalizedBaseUri}${tokenId}.png`;
  } else {
    // Fallback to placeholder
    imageUrl = `ipfs://PLACEHOLDER/${tokenId}.png`;
  }

  // Generate metadata object
  const metadata = generateMetadata({
    projectId,
    tokenId,
    name: `${projectName} #${tokenId}`,
    description: description || `${projectName} NFT collection - Token #${tokenId}`,
    imageUrl,
    attributes
  });

  // Save to file
  const metadataPath = await saveMetadataFile(projectId, tokenId, metadata);

  // Save to database
  const dbRecord = await saveMetadataToDatabase(
    projectId,
    tokenId,
    imagePath,
    metadataPath,
    attributes
  );

  return {
    metadata,
    metadataPath,
    dbRecord
  };
}

/**
 * Generate metadata for multiple NFTs
 * @param {string} projectId - UUID of the project
 * @param {string} projectName - Name of the project
 * @param {Array} nftData - Array of NFT data with tokenId, imagePath, attributes
 * @param {Object} options - Generation options
 * @returns {Promise<Object>} Generation results
 */
async function generateCollectionMetadata(projectId, projectName, nftData, options = {}) {
  const {
    description = `${projectName} NFT collection`,
    baseUri = null,
    onProgress = null
  } = options;

  const results = [];
  const errors = [];
  const total = nftData.length;

  console.log(`\n📝 Starting metadata generation for ${total} NFTs`);
  if (baseUri) {
    console.log(`📦 Using Base URI: ${baseUri}`);
  } else {
    console.log(`⚠️  No Base URI provided - using placeholder`);
  }

  for (let i = 0; i < nftData.length; i++) {
    const { tokenId, imagePath, attributes } = nftData[i];

    try {
      const result = await generateAndSaveMetadata({
        projectId,
        projectName,
        tokenId,
        imagePath,
        attributes,
        description,
        baseUri
      });

      results.push(result);

      // Progress callback
      if (onProgress) {
        onProgress({
          current: i + 1,
          total,
          percentage: Math.round(((i + 1) / total) * 100)
        });
      }

      console.log(`✓ Metadata for NFT #${tokenId} saved (${i + 1}/${total})`);
    } catch (error) {
      const errorMsg = `Failed to generate metadata for NFT #${tokenId}: ${error.message}`;
      console.error(`✗ ${errorMsg}`);
      errors.push({ tokenId, error: errorMsg });
    }
  }

  console.log(`\n✅ Metadata generation complete: ${results.length}/${total} successful`);
  if (errors.length > 0) {
    console.log(`⚠️  ${errors.length} errors occurred`);
  }

  return {
    successful: results,
    errors,
    total,
    successCount: results.length,
    errorCount: errors.length
  };
}

/**
 * Update base URI placeholder in metadata files
 * @param {string} projectId - UUID of the project
 * @param {string} baseUri - Base URI (e.g., "ipfs://Qm..." or "https://metadata.example.com/")
 * @returns {Promise<number>} Number of files updated
 */
async function updateMetadataBaseUri(projectId, baseUri) {
  const metadataDir = path.join(process.cwd(), 'output', projectId, 'metadata');

  try {
    const files = await fs.readdir(metadataDir);
    const jsonFiles = files.filter(f => f.endsWith('.json'));
    let updated = 0;

    for (const file of jsonFiles) {
      const filePath = path.join(metadataDir, file);
      const content = await fs.readFile(filePath, 'utf8');
      const metadata = JSON.parse(content);

      // Extract token ID from filename
      const tokenId = file.replace('.json', '');

      // Update image URL
      metadata.image = `${baseUri}${tokenId}.png`;

      // Write back
      await fs.writeFile(filePath, JSON.stringify(metadata, null, 2), 'utf8');
      updated++;
    }

    console.log(`✅ Updated ${updated} metadata files with base URI: ${baseUri}`);
    return updated;
  } catch (error) {
    throw new Error(`Failed to update metadata base URI: ${error.message}`);
  }
}

/**
 * Get metadata for a specific token from database
 * @param {string} projectId - UUID of the project
 * @param {number} tokenId - Token ID
 * @returns {Promise<Object>} Token metadata from database
 */
async function getTokenMetadata(projectId, tokenId) {
  const { data, error } = await supabase
    .from('cro_212hub_generated_tokens')
    .select('*')
    .eq('project_id', projectId)
    .eq('token_id', tokenId)
    .single();

  if (error) {
    throw new Error(`Failed to fetch token metadata: ${error.message}`);
  }

  return data;
}

/**
 * Get all metadata for a project from database
 * @param {string} projectId - UUID of the project
 * @returns {Promise<Array>} All token metadata
 */
async function getAllTokenMetadata(projectId) {
  const { data, error } = await supabase
    .from('cro_212hub_generated_tokens')
    .select('*')
    .eq('project_id', projectId)
    .order('token_id', { ascending: true });

  if (error) {
    throw new Error(`Failed to fetch token metadata: ${error.message}`);
  }

  return data;
}

module.exports = {
  generateMetadata,
  saveMetadataFile,
  saveMetadataToDatabase,
  generateAndSaveMetadata,
  generateCollectionMetadata,
  updateMetadataBaseUri,
  getTokenMetadata,
  getAllTokenMetadata
};
